### ISSUE TITLE
Attack an ensemble of models

### ISSUE THREAD

**Issue by qilong-zhang** [Muzammal-Naseer/CDA#3]
Hi Muzammal,

Have you test your approach when white-box models are an ensemble of Inc-v3, Inc-v4, IncRes-v2 and Res-152? The reported results in Tab.6 is really impressive! And I want to know if you attack an ensemble of models, How much can your experimental results improve?

Thanks~

**Comment by Muzammal-Naseer** [comment]
Hi,

We haven't experimented with ensemble. All of the generators are trained against single model at a time. The pretrained generators are available. You are welcome to attack ensemble of models.

Best Regards,
